name: anime
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  animated_read_more_text: ^0.0.6
  animated_theme_switcher: ^2.0.10
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  chewie: ^1.7.5
  connectivity_plus: ^5.0.2
  dio: ^5.4.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_riverpod: ^2.4.10
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.10+1
  flutter_tabler_icons: ^1.25.0
  go_router: ^13.2.0
  google_fonts: ^6.2.1
  iconsax: ^0.0.8
  image_picker: ^1.0.7
  palette_generator: ^0.3.3+3
  path_provider: ^2.1.2
  rename: ^3.0.2
  shimmer: ^3.0.0
  simple_ripple_animation: ^0.0.9
  text_scroll: ^0.2.0
  video_player: ^2.8.3
  video_thumbnail: ^0.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/